fix reload
GeyserMC/Floodgate pull request #413
Opened 2023-05-21 00:02 UTC by Tjorven-Liebe

after a while of using your software, I regcognised, that your reload wasn't working that well. 
I guess that I've fixed it in 2 lines. If not teach me.

2023-06-20 19:04 UTC, JonasDevDE approved these changes

2023-06-20 20:28 UTC, Konicai commented
I can't speak for Tim but I'm pretty sure this should target the development branch if it hasn't already been fixed there.

2023-06-20 22:41 UTC, rtm516 requested changes

2023-06-20 22:41 UTC, rtm516 commented on spigot/src/main/java/org/geysermc/floodgate/inject/spigot/SpigotInjector.java
> +        if (future.channel().pipeline().get("floodgate-init")!=null)
```suggestion
        if (future.channel().pipeline().get("floodgate-init") != null)
```

2023-08-27 16:09 UTC, Tim203 commented
Hi, the reason this PR has not been merged is because I think this doesn't actually solve the issue (only on the surface.)
Some form of reload support is planned, but I don't think this is the way.

2023-09-25 19:10 UTC, Tjorven-Liebe commented
Well if you think so.
I will close this PR now.

2023-09-25 19:10 UTC, closed without merging